### PR TITLE
Add MySQL to nova-compute

### PR DESCRIPTION
**Pull request by saptaktakalkar**
JIRA: [AN-108](https://midobugs.atlassian.net/login?dest-url=%2Fbrowse%2FAN-108&permission-violation=true)

### CODE REVIEW

**Comment by saptaktakalkar** [comment]
@abelboldu @ryo-tagami Not sure what to do with this PR.
It's failing at: https://travis-ci.org/saptaktakalkar/openstack-nova-compute/jobs/149442616#L1518
Should we just merged it anyway?

**Comment by abelboldu** [comment]
@ryo @saptaktakalkar  Once we remove docker here, we can rebase so the  test passes.

**Comment by ryo-tagami** [comment]
I'll prepare a patch to remove Docker from Travis CI with other cumulative updates. Please give me one day.

**Comment by saptaktakalkar** [comment]
@abelboldu @ryo-tagami I have uploaded the patch to take care of everything. Please review: https://github.com/openstack-ansible-galaxy/openstack-nova-compute/pull/1/commits/792808f2e413a8f3e45ec29f20ee0dc0811a9093 and let me know if any more update needs to make

**Comment by abelboldu** [comment]
@saptak It's better to separate commits per topic, but looks good so I'm merging

**Pull request merged**
